In [1]:
import pandas as pd

In [2]:
# Get url for table
url = 'https://en.wikipedia.org/wiki/Gun_violence_in_the_United_States_by_state'

In [3]:
#Bring table into pandas
tables = pd.read_html(url)
tables

[        0             1             2             3             4        5
 0  Lowest  1st Quartile  2nd Quartile  3rd Quartile  4th Quartile  Highest,
                        0                                          1  \
 0                  State  Population (total inhabitants) (2015) [2]
 1                Alabama                                    4853875
 2                 Alaska                                     737709
 3                Arizona                                    6817565
 4               Arkansas                                    2977853
 5             California                                   38993940
 6               Colorado                                    5448819
 7            Connecticut                                    3584730
 8               Delaware                                     944076
 9   District of Columbia                                     670377
 10               Florida                                   20244914
 11               Georgia                                   10199398
 12                Hawaii                                    1425157
 13                 Idaho                                    1652828
 14              Illinois                                   12839047
 15               Indiana                                    6612768
 16                  Iowa                                    3121997
 17                Kansas                                    2906721
 18              Kentucky                                    4424611
 19             Louisiana                                    4668960
 20                 Maine                                    1329453
 21              Maryland                                    5994983
 22         Massachusetts                                    6784240
 23              Michigan                                    9917715
 24             Minnesota                                    5482435
 25           Mississippi                                    2989390
 26              Missouri                                    6076204
 27               Montana                                    1032073
 28              Nebraska                                    1893765
 29                Nevada                                    2883758
 30         New Hampshire                                    1330111
 31            New Jersey                                    8935421
 32            New Mexico                                    2080328
 33              New York                                   19747183
 34        North Carolina                                   10035186
 35          North Dakota                                     756835
 36                  Ohio                                   11605090
 37              Oklahoma                                    3907414
 38                Oregon                                    4024634
 39          Pennsylvania                                   12791904
 40          Rhode Island                                    1055607
 41        South Carolina                                    4894834
 42          South Dakota                                     857919
 43             Tennessee                                    6595056
 44                 Texas                                   27429639
 45                  Utah                                    2990632
 46               Vermont                                     626088
 47              Virginia                                    8367587
 48            Washington                                    7160290
 49         West Virginia                                    1841053
 50             Wisconsin                                    5767891
 51               Wyoming                                     586107

                                                     2  \
 0   Murders andNonnegligentManslaughter (total dea...
 1                                                 348
 2                                                  59
 3                                                 309
 4                                                 181
 5                                                1861
 6                                                 176
 7                                                 117
 8                                                  63
 9                                                 162
 10                                               1041
 11                                                615
 12                                                 19
 13                                                 32
 14                                                744
 15                                                373
 16                                                 72
 17                                                128
 18                                                209
 19                                                481
 20                                                 23
 21                                                516
 22                                                128
 23                                                571
 24                                                133
 25                                                259
 26                                                502
 27                                                 36
 28                                                 62
 29                                                178
 30                                                 14
 31                                                363
 32                                                117
 33                                                609
 34                                                517
 35                                                 21
 36                                                500
 37                                                234
 38                                                 99
 39                                                658
 40                                                 29
 41                                                399
 42                                                 32
 43                                                406
 44                                               1316
 45                                                 54
 46                                                 10
 47                                                383
 48                                                211
 49                                                 70
 50                                                240
 51                                                 16

                                     3                                      4  \
 0   Murders (total deaths) (2015) [3]  Gun Murders (total deaths) (2015) [3]
 1                                3[a]                                   3[a]
 2                                  57                                     39
 3                                 278                                    171
 4                                 164                                    110
 5                                1861                                   1275
 6                                 176                                    115
 7                                 107                                     73
 8                                  63                                     52
 9                                 162                                    121
 10                              — [b]                                  — [b]
 11                                565                                    464
 12                                 19                                      4
 13                                 30                                     24
 14                             497[a]                                 440[a]
 15                                272                                    209
 16                                 72                                     49
 17                                125                                     91
 18                                209                                    141
 19                                474                                    379
 20                                 23                                     16
 21                                372                                    279
 22                                126                                     81
 23                                571                                    389
 24                                133                                     79
 25                                159                                    126
 26                                499                                    418
 27                                 36                                     18
 28                                 61                                     43
 29                                177                                    113
 30                                 14                                      8
 31                                353                                    255
 32                                 94                                     56
 33                                611                                    383
 34                                506                                    353
 35                                 17                                      9
 36                                480                                    316
 37                                233                                    149
 38                                 71                                     34
 39                                651                                    497
 40                                 27                                     10
 41                                394                                    312
 42                                 27                                     12
 43                                402                                    297
 44                               1276                                    906
 45                                 54                                     34
 46                                 10                                      8
 47                                383                                    275
 48                                209                                    141
 49                                 57                                     30
 50                                238                                    170
 51                                 16                                     10

                               5  \
 0   GunOwnership (%) (2013) [4]
 1                          48.9
 2                          61.7
 3                          32.3
 4                          57.9
 5                          20.1
 6                          34.3
 7                          16.6
 8                           5.2
 9                          25.9
 10                         32.5
 11                         31.6
 12                         45.1
 13                         56.9
 14                         26.2
 15                         33.8
 16                         33.8
 17                         32.2
 18                         42.4
 19                         44.5
 20                         22.6
 21                         20.7
 22                         22.6
 23                         28.8
 24                         36.7
 25                         42.8
 26                         27.1
 27                         52.3
 28                         19.8
 29                         37.5
 30                         14.4
 31                         11.3
 32                         49.9
 33                         10.3
 34                         28.7
 35                         47.9
 36                         19.6
 37                         31.2
 38                         26.6
 39                         27.1
 40                          5.8
 41                         44.4
 42                         35.0
 43                         39.4
 44                         35.7
 45                         31.9
 46                         28.8
 47                         29.3
 48                         27.7
 49                         54.2
 50                         34.7
 51                         53.8

                                                     6  \
 0   Murder andNonnegligentManslaughterRate (per 10...
 1                                                 7.2
 2                                                 8.0
 3                                                 4.5
 4                                                 6.1
 5                                                 4.8
 6                                                 3.2
 7                                                 3.3
 8                                                 6.7
 9                                                24.2
 10                                                5.1
 11                                                6.0
 12                                                1.3
 13                                                1.9
 14                                                5.8
 15                                                5.6
 16                                                2.3
 17                                                4.4
 18                                                4.7
 19                                               10.3
 20                                                1.7
 21                                                8.6
 22                                                1.9
 23                                                5.8
 24                                                2.4
 25                                                8.7
 26                                                8.3
 27                                                3.5
 28                                                3.3
 29                                                6.2
 30                                                1.1
 31                                                4.1
 32                                                5.6
 33                                                3.1
 34                                                5.2
 35                                                2.8
 36                                                4.3
 37                                                6.0
 38                                                2.5
 39                                                5.1
 40                                                2.7
 41                                                8.2
 42                                                3.7
 43                                                6.2
 44                                                4.8
 45                                                1.8
 46                                                1.6
 47                                                4.6
 48                                                2.9
 49                                                3.8
 50                                                4.2
 51                                                2.7

                                    7                                    8
 0   Murder Rate (per 100,000) (2015)  GunMurder Rate (per 100,000) (2015)
 1                             0.1[a]                               0.1[a]
 2                                7.7                                  5.3
 3                                4.1                                  2.5
 4                                5.5                                  3.7
 5                                4.8                                  3.3
 6                                3.2                                  2.1
 7                                3.0                                  2.0
 8                                6.7                                  5.5
 9                               24.2                                 18.0
 10                             — [b]                                — [b]
 11                               5.5                                  4.5
 12                               1.3                                  0.3
 13                               1.8                                  1.5
 14                            3.9[a]                               3.4[a]
 15                               4.1                                  3.2
 16                               2.3                                  1.6
 17                               4.3                                  3.1
 18                               4.7                                  3.2
 19                              10.2                                  8.1
 20                               1.7                                  1.2
 21                               6.2                                  4.7
 22                               1.9                                  1.2
 23                               5.8                                  3.9
 24                               2.4                                  1.4
 25                               5.3                                  4.2
 26                               8.2                                  6.9
 27                               3.5                                  1.7
 28                               3.2                                  2.3
 29                               6.1                                  3.9
 30                               1.1                                  0.6
 31                               4.0                                  2.9
 32                               4.5                                  2.7
 33                               3.1                                  1.9
 34                               5.0                                  3.5
 35                               2.2                                  1.2
 36                               4.1                                  2.7
 37                               6.0                                  3.8
 38                               1.8                                  0.8
 39                               5.1                                  3.9
 40                               2.6                                  0.9
 41                               8.0                                  6.4
 42                               3.1                                  1.4
 43                               6.1                                  4.5
 44                               4.7                                  3.3
 45                               1.8                                  1.1
 46                               1.6                                  1.3
 47                               4.6                                  3.3
 48                               2.9                                  2.0
 49                               3.1                                  1.6
 50                               4.1                                  2.9
 51                               2.7                                  1.7  ,
                                                     0  \
 0                vteUnited States state-related lists
 1   List of states and territories of the United S...
 2                                        Demographics
 3                                             Economy
 4                                         Environment
 5                                           Geography
 6                                          Government

In [4]:
type(tables)

list

In [5]:
# Convert table to pandas dataframe and add column titles
gun_df = tables[1]
gun_df.columns = ['State', 'Total Population', 'Murders and Nonnegligent Manslaughter', 'Murders', 
                  'Gun Murders', 'Gun Ownership (%)', 'Murders and Nonnegligent Manslaughter Rate (%)', 'Murder Rate (%)', 'Gun Murder Rate (%)']
gun_df.head()

,State,Total Population,Murders and Nonnegligent Manslaughter,Murders,Gun Murders,Gun Ownership (%),Murders and Nonnegligent Manslaughter Rate (%),Murder Rate (%),Gun Murder Rate (%)
0,State,Population (total inhabitants) (2015) [2],Murders andNonnegligentManslaughter (total dea...,Murders (total deaths) (2015) [3],Gun Murders (total deaths) (2015) [3],GunOwnership (%) (2013) [4],Murder andNonnegligentManslaughterRate (per 10...,"Murder Rate (per 100,000) (2015)","GunMurder Rate (per 100,000) (2015)"
1,Alabama,4853875,348,3[a],3[a],48.9,7.2,0.1[a],0.1[a]
2,Alaska,737709,59,57,39,61.7,8.0,7.7,5.3
3,Arizona,6817565,309,278,171,32.3,4.5,4.1,2.5
4,Arkansas,2977853,181,164,110,57.9,6.1,5.5,3.7

In [6]:
#Drop extra row
gun_df = gun_df.iloc[1:]
gun_df.head()

,State,Total Population,Murders and Nonnegligent Manslaughter,Murders,Gun Murders,Gun Ownership (%),Murders and Nonnegligent Manslaughter Rate (%),Murder Rate (%),Gun Murder Rate (%)
1,Alabama,4853875,348,3[a],3[a],48.9,7.2,0.1[a],0.1[a]
2,Alaska,737709,59,57,39,61.7,8.0,7.7,5.3
3,Arizona,6817565,309,278,171,32.3,4.5,4.1,2.5
4,Arkansas,2977853,181,164,110,57.9,6.1,5.5,3.7
5,California,38993940,1861,1861,1275,20.1,4.8,4.8,3.3

In [7]:
#Set State as index
gun_df.set_index('State', inplace = True)
gun_df.head()

,Total Population,Murders and Nonnegligent Manslaughter,Murders,Gun Murders,Gun Ownership (%),Murders and Nonnegligent Manslaughter Rate (%),Murder Rate (%),Gun Murder Rate (%)
State,,,,,,,,
Alabama,4853875,348,3[a],3[a],48.9,7.2,0.1[a],0.1[a]
Alaska,737709,59,57,39,61.7,8.0,7.7,5.3
Arizona,6817565,309,278,171,32.3,4.5,4.1,2.5
Arkansas,2977853,181,164,110,57.9,6.1,5.5,3.7
California,38993940,1861,1861,1275,20.1,4.8,4.8,3.3

In [8]:

#Clean up records with additions
gun_df['Murders'] = gun_df['Murders'].map(lambda x: x.rstrip('[a]').rstrip('[b]'))
gun_df['Gun Murders'] = gun_df['Gun Murders'].map(lambda x: x.rstrip('[a]').rstrip('[b]'))
gun_df['Murder Rate (%)'] = gun_df['Murder Rate (%)'].map(lambda x: x.rstrip('[a]').rstrip('[b]'))
gun_df['Gun Murder Rate (%)'] = gun_df['Gun Murder Rate (%)'].map(lambda x: x.rstrip('[a]').rstrip('[b]'))

#Replace — with NaN 
gun_df['Murders'] = gun_df['Murders'].replace({'—':'NULL'})
gun_df['Gun Murders'] = gun_df['Gun Murders'].replace({'—':'NULL'})
gun_df['Murder Rate (%)'] = gun_df['Murder Rate (%)'].replace({'—':'NULL'})
gun_df['Gun Murder Rate (%)'] = gun_df['Gun Murder Rate (%)'].replace({'—':'NULL'})
gun_df.head(20)

C:\Users\kamrk\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\kamrk\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\kamrk\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\kamrk\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\kamrk\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\kamrk\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\kamrk\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\kamrk\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

,Total Population,Murders and Nonnegligent Manslaughter,Murders,Gun Murders,Gun Ownership (%),Murders and Nonnegligent Manslaughter Rate (%),Murder Rate (%),Gun Murder Rate (%)
State,,,,,,,,
Alabama,4853875,348,3,3,48.9,7.2,0.1,0.1
Alaska,737709,59,57,39,61.7,8.0,7.7,5.3
Arizona,6817565,309,278,171,32.3,4.5,4.1,2.5
Arkansas,2977853,181,164,110,57.9,6.1,5.5,3.7
California,38993940,1861,1861,1275,20.1,4.8,4.8,3.3
Colorado,5448819,176,176,115,34.3,3.2,3.2,2.1
Connecticut,3584730,117,107,73,16.6,3.3,3.0,2.0
Delaware,944076,63,63,52,5.2,6.7,6.7,5.5
District of Columbia,670377,162,162,121,25.9,24.2,24.2,18.0
Florida,20244914,1041,—,—,32.5,5.1,—,—
Georgia,10199398,615,565,464,31.6,6.0,5.5,4.5
Hawaii,1425157,19,19,4,45.1,1.3,1.3,0.3
Idaho,1652828,32,30,24,56.9,1.9,1.8,1.5
Illinois,12839047,744,497,440,26.2,5.8,3.9,3.4
Indiana,6612768,373,272,209,33.8,5.6,4.1,3.2
Iowa,3121997,72,72,49,33.8,2.3,2.3,1.6
Kansas,2906721,128,125,91,32.2,4.4,4.3,3.1
Kentucky,4424611,209,209,141,42.4,4.7,4.7,3.2
Louisiana,4668960,481,474,379,44.5,10.3,10.2,8.1
Maine,1329453,23,23,16,22.6,1.7,1.7,1.2

In [9]:
# Write to CSV for uploading to SQL

gun_df.to_csv('resources/gun_murder_rates.csv',index=True,header = True)